<?php

namespace MidnightLabs;

class Short_URL {

	/*
	 * Class variables
	 */
	public static $options_name = 'rb_short_url';
	public static $options_defaults = array(
		'base_url' => '',
	);
	public static $generic_base_url = '';

	private static $instance;


	public static function get_instance() {
		if ( ! isset( self::$instance ) ) {
			self::$instance = new Short_URL;
			self::$instance->init();
			self::$instance->setup_actions();
			self::$instance->setup_filters();
		}
		return self::$instance;
	}

	/**
	 * Set default values for class variables
	 */
	public function init() {

		$home_url = parse_url( network_home_url() );
		self::$generic_base_url = $home_url['host'];
	}


	/**
	 * Initialize action handlers
	 */
	public function setup_actions() {
		add_action( 'admin_init', array( $this, 'action_admin_init' ) );
		add_action( 'admin_menu', array( $this, 'action_admin_menu' ) );

	}

	/**
	 * Initialize filter handlers
	 */
	public function setup_filters() {

		add_filter( 'get_shortlink', array( $this, 'filter_get_shortlink' ), 99, 1 );
	}


	/*
	 * Register setting
	 */
	public function action_admin_init() {
		register_setting( self::$options_name, self::$options_name, array( $this, 'sanitize_options' ) );
	}


	/*
	 * Register custom Tools page & menu item
	 */
	public function action_admin_menu() {
		add_management_page( 'URL Shortener', 'URL Shortener', 'manage_options', self::$options_name, array( $this, 'screen_options' ) );
	}


	/*
	 * Display the custom Tools page for managing the URL shortener options
	 */
	public function screen_options() {
		$options = get_option( self::$options_name, self::$options_defaults );

	?>
		<div class="wrap">
			<h2>Custom URL Shortener Options</h2>

			<?php if( isset( $_GET['settings-updated'] ) && ( $_GET['settings-updated'] == 'true' ) ) { ?>
				<div id="message" class="updated">
					<p><strong>Settings saved.</strong></p>
				</div>
			<?php } ?>

			<p>The goal of this custom URL shortener is to provide even shorter short links to your site's pages. The setup of a URL shortener typically requires you to register your own domain name (something like goo.gl) and configure it to redirect to your primary domain (<?php echo esc_html( self::$generic_base_url ); ?>). There are other ways to accomplish this, but that's the easiest and best way to use this URL shortener plugin.</p>
			<p>After setting the base URL below, any shortlinks generated by WordPress will use this rather than your primary domain.</p>

			<form action="options.php" method="post">
				<?php settings_fields( self::$options_name ); ?>
				<table class="form-table">
					<tr>
						<th scope="row"><label for="base_url">Base URL:</label></th>
						<td><input type="text" id="base_url" value="<?php echo esc_url( $options[ 'base_url' ] ); ?>" name="<?php echo esc_attr( self::$options_name ); ?>[base_url]" /></td>
						<td><span class="description">What to replace '<strong>http://<?php echo esc_html( self::$generic_base_url ); ?></strong>' with this when generating short urls.</span></td>
					</tr>
				</table>
				<p><input type="submit" value="Save Changes" class="button-primary" /></p>
			</form>
		</div>
	<?php
	}


	/*
	 * Sanitize options
	 */
	public function sanitize_options( $options ) {
		$options_sanitized = array();

		foreach( $options as $key => $value ) {
			switch( $key ) {
				case 'base_url':
					$options_sanitized[ $key ] = esc_url_raw( $value );
				break;
			}
		}

		return $options_sanitized;
	}


	/*
	 * Filter the shortlink to replace the default home URL with the custom URL
	 */
	public function filter_get_shortlink( $shortlink = '' ) {
		$options = get_option( self::$options_name, self::$options_defaults );

		if( isset( $options['base_url'] ) && !empty( $options['base_url'] ) && !empty( $shortlink ) ) {
			// only proceed if there is a custom URL set and there is already a shortlink to filter

			// parse the custom URL down to just the host
			$base_url = parse_url( esc_url( $options['base_url'] ) );
			$base_url = $base_url['host'];

			// replace the generic site host with the custom URL host
			$shortlink = str_replace( self::$generic_base_url, $base_url, $shortlink );
		}

		return $shortlink;
	}


	/*
	 * Handles cleanup of any saved settings for the plugin so we're good neighbors
	 */
	public function on_deactivation() {
		// delete the options
		delete_option( 'rb_short_url' );

		// unregister the setting
		unregister_setting( 'rb_short_url', 'rb_short_url', array( 'MidnightLabs\Short_URL', 'sanitize_options' ) );
	}

}


/*
 * Register the plugin's deactivation handler
 */
register_deactivation_hook( __FILE__, array( 'MidnightLabs\Short_URL', 'on_deactivation' ) );
